# Generated by Django 3.2.5 on 2021-07-10 20:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm1_tr', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1', models.CharField(max_length=6)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_tr', models.CharField(max_length=50)),
                ('adm0', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Incidences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('localname', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Incidences',
                'db_table': 'incident',
            },
            managers=[
                ('objects_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
