# Generated by Django 3.2.5 on 2021-07-11 16:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('adm2_tr', models.CharField(max_length=50)),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm1_tr', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1', models.CharField(max_length=6)),
                ('pcode', models.CharField(max_length=9)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
